#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other shells, you may want to try them.
#
#   (2) Putting it in a background job will cause it to ignore the terminal
#       interrupt character Ctrl+C, so you may want to build a wrapper script
#       that will call this one, e.g. using "screen" or something similar.
#
#   (3) When used with `sh -c`, this script does not work at all if the
#       JAVA_HOME or JAVA_OPTS are not already exported in the shell.
#
##############################################################################

if [ "$(uname)" = "Darwin" ] ; then
    APP_NAME="Gradle"
    APP_DIRNAME=$( cd "${APP_DIRNAME:-.}" && pwd -P )
else
    APP_NAME="app"
    APP_DIRNAME=$( cd "${APP_DIRNAME:-.}" && pwd -L )
fi

APP_HOME="${APP_DIRNAME}"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*" >&2
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, maxproc is called OPEN_MAX.
        MAX_FD=$( getconf OPEN_MAX ) ||
            # Try the GNU getconf and specify the value on 'sysctl -a | grep' in the unlikely case of a miss.
            MAX_FD=$( sysctl -n hw.maxfiles ) ||
            MAX_FD=$( sysctl -n hw.maxproc ) ||
            MAX_FD=262144

        ;;
    esac
    # ulimit -n $MAX_FD
fi

if expr a : '\(a\)' >/dev/null 2>&1 ; then
    expr_result=:
else
    expr_result=expr
fi

if [ "$cygwin" ] || [ "$msys" ] ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )
fi

if [ "$OSTYPE" = cygwin ] ; then
    APP_HOME=$( cygpath --path --windows "$APP_HOME" )
    CLASSPATH=$( cygpath --path --windows "$CLASSPATH" )
else
    APP_HOME=$( eval echo "$APP_HOME" )
    CLASSPATH=$( eval echo "$CLASSPATH" )
fi

# Now convert the arguments - kludge to limit ourselves to /bin/sh
for arg do
    if
        case $arg in                                #(
          -*)   false ;;                            # don't mess with options #(
          /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                [ -e "$t" ] ;;                      #(
          *)    false ;;
        esac
    then
        arg=$( cygpath --path --windows "$arg" )
    fi
    # Roll the args list around exactly as many times as the number of args.
    set -- "$@" "$arg"
done

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
